### ISSUE TITLE
Modify Image:drawImage() behavior

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/api#59] opened 2021-10-04 16:39 UTC
Currently, `dstImg: drawImage (srcImg, position)`, draws the `srcImg` at the position referred to the limits of` dstImg`. If the input argument `position` is outside the limits of `dstImg`,` srcImg` is not drawn in `dstImg` (I think this would be more useful if dstImg is enlarged according to the input arguments:` srcImg` and ` position`).

Also, transparent pixels override opaque colors (I think this would be more intuitive to do an alpha composition, another option is to include an input arg flag as `composition` selection).

Low priority.

**Comment by dacap** [comment] 2021-10-04 16:54
Related to #31

**Comment by dacap** [comment] 2021-10-04 16:56
Did you check if part of the `srcImg` is painted if the position is negative? (e.g. `position={-1,-1}`)

**Comment by dacap** [comment] 2021-10-04 17:02
`Image:drawImage()` shouldn't modify the size of the `dstImg`, it should only draw in the available are of the `dstImg` and clip anything that is outside its area.

**Comment by dacap** [comment] 2021-10-04 17:12
We can close this because #31 is the composition part. The clipping is the expected behavior.

**Closed by dacap** 2021-10-04 17:12 UTC
